### ISSUE TITLE
[Bug] [ZAMNHLMP] Missing labels on Change Your Team menu

### ISSUE THREAD

**Issue by ry13y04** [phoenixprojectsoftware/HL1-Games#2]
**Describe the bug**
On the Choose Your Team page, all labels are missing.

**To Reproduce**
1. Set gamemode to 'tdm'
2. Start the server
3. See error

**Expected behavior**
All labels should be correct.

**Screenshots**
![Screenshot_71](https://user-images.githubusercontent.com/75205875/121092854-1a247580-c7e4-11eb-8240-1f50b58a8813.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Game Half-Life: Zombies Ate My Neighbours Multiplayer
 - Version 2.5

**Additional context**
N/A

**Comment by ry13y04** [comment]
This issue is still present.
![image](https://user-images.githubusercontent.com/75205875/121276721-1ae20800-c8c7-11eb-88de-d46a07147275.png)

**Comment by sabianroberts** [comment]
https://github.com/phoenixprojectsoftware/zamnhlmp/commit/d7643af580b6a2bed68a108b6b9014b482477537
